version: '3.8'

services:
  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    user: "root"
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # /var/lib/grafana/data:/var/lib/grafana
      - ${GRAFANA_SOURCE_DATA_VOLUME}:${GRAFANA_TARGET_DATA_VOLUME}
    env_file:
      - 'env.grafana'
    depends_on:
      - influxdb
    #networks:
    #  - internal
    privileged: true
    
  influxdb:
    image: influxdb:${INFLUXDB_TAG}
    user: 'root'
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ${INFLUXDB_SOURCE_DATA_VOLUME}:${INFLUXDB_TARGET_DATA_VOLUME}
      - ${INFLUXDB2_SOURCE_DATA_VOLUME}:${INFLUXDB2_TARGET_DATA_VOLUME}
      - ${INFLUXDB2_SOURCE_CONFIG_VOLUME}:${INFLUXDB2_TARGET_CONFIG_VOLUME}
    env_file:
      - 'env.influxdb'
    #networks:    
    #  - internal
    privileged: true
