version: '3.8'

services:
  influxdb:
    image: influxdb:${INFLUXDB2_TAG}
    container_name: influxdb
    user: 'root'
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb20-data:${INFLUXDB2_TARGET_DATA_VOLUME}
      - ./influxdb20-config:${INFLUXDB2_TARGET_CONFIG_VOLUME}
    env_file:
      - './influxdb/env.influxdb'
    networks:    
      - internal
    privileged: true

  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    container_name: grafana
    user: "root"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # /var/lib/grafana/data:/var/lib/grafana
      #- ${GRAFANA_SOURCE_DATA_VOLUME}:${GRAFANA_TARGET_DATA_VOLUME}
      - ./grafana-data:${GRAFANA_TARGET_DATA_VOLUME}
    env_file:
      - './grafana/env.grafana'
    depends_on:
      - influxdb
    networks:
      - internal
    privileged: true

  telegraf:
    image: telegraf:${TELEGRAF_TAG}
    container_name: telegraf
    user: "root"
    restart: always
    volumes:
      - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - internal
    depends_on: 
      - influxdb
    privileged: true

networks:
  internal:

volumes:
  grafana-data:
    external: true

  influxdb18-data:
    external: true

  influxdb20-data:
    external: true

  influxdb20-config:
    external: true