version: '3.8'

services:
  influxdb:
    image: influxdb:${INFLUXDB_TAG}
    container_name: influxdb
    user: 'root'
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb18-data:${INFLUXDB_TARGET_DATA_VOLUME}
    env_file:
      - 'env.influxdb'
    networks:    
      - internal
    privileged: true

  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    container_name: grafana
    user: "root"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:${GRAFANA_TARGET_DATA_VOLUME}
    env_file:
      - 'env.grafana'
    depends_on:
      - influxdb
    networks:
      - internal
    privileged: true

  telegraf:
    image: telegraf:${TELEGRAF_TAG}
    container_name: telegraf
    user: "root"
    restart: always
    volumes:
      - "./telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - internal
    privileged: true

  kapacitor:
    image: kapacitor:${KAPACITOR_TAG}
    container_name: kapacitor
    user: "root"
    restart: always
    ports: 
      - 9092:9092
    volumes:
      - ./kapacitor-data:${KAPACITOR_TARGET_DATA_VOLUME}
    env_file: 
      - 'env.kapacitor'
    networks: 
      - internal
    privileged: true

networks:
  internal:

volumes:
  grafana-data:
    external: true

  influxdb18-data:
    external: true